export AMZN="https://www.amazon.com/s?i=toys-and-games&ref=nb_sb_noss_1&k="
export BGC="https://boardgameco.com/pages/search-results-page?q="
export CSI="https://www.coolstuffinc.com/main_search.php?pa=searchOnName&page=1&resultsPerPage=25&q="
export GN="https://www.gamenerdz.com/search-results-page?q="
export MM="https://www.miniaturemarket.com/searchresults/?q="
export NK="https://www.nobleknight.com/Search?text="

open ${AMZN}"${1}"
open ${BGC}"${1}"
open ${CSI}"${1}"
open ${GN}"${1}"
open ${MM}"${1}"
open ${NK}"${1}"
